"""initial

Revision ID: fe8ae7c94c74
Revises: ef53c66fd135
Create Date: 2024-03-10 14:11:22.621313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8ae7c94c74'
down_revision = 'ef53c66fd135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
